#!/bin/bash
# The only command site2's syncoid key may run on infra (rung 5 › E: "an account allowed only to send
# and hold snapshots of the datasets that matter"). Unraid's sshd admits root alone (AllowUsers root,
# regenerated by Unraid), so the "account" is a root key restricted in /root/.ssh/authorized_keys:
#   restrict,from="100.64.0.12",command="/mnt/data/system/seed-bin/zfs-send-guard.sh" ssh-ed25519 … syncoid@site2 seed
# and this guard, which runs a command only if it is one of the few that syncoid sends to a source
# (sanoid 2.3.0, pull mode, --no-sync-snap --use-hold --no-resume --compress=none):
#   exit                                      (syncoid's ssh control master)
#   echo -n                                   (its connection test; found on the first run, 20260929)
#   command -v <tool>                         (its checks for mbuffer, pv, lzop, zstd, socat, busybox)
#   zpool get -o value -H feature@<f> data    (its resume-support check)
#   zfs get|list <read-only options> <an allowed dataset or one of its snapshots>
#   zfs send [-n -v -P -I -i] <snapshots of one allowed dataset> [| mbuffer -q -s 128k -m 16M]
#   zfs hold|release syncoid_<id> <a snapshot of an allowed dataset>
# Nothing else: no snapshot, destroy, rename, receive, set, no resume token (it could name any
# dataset), no shell. The command line may hold only a narrow set of characters, and syncoid's single
# quotes are dropped before matching (dataset and snapshot names here contain none). Every command is
# logged (seed-state/zfs-send-guard.log, last 2000 lines), refusals marked DENIED.
set -u
ALLOWED="data/documents data/finance data/photos data/appdata"
LOG=/mnt/data/system/seed-state/zfs-send-guard.log
c=${SSH_ORIGINAL_COMMAND:-}
log() { { echo "$(date -u +%FT%TZ) $1: ${c:0:400}"; } >> "$LOG" 2>/dev/null
        [ "$(wc -l < "$LOG" 2>/dev/null || echo 0)" -gt 4000 ] && tail -2000 "$LOG" > "$LOG.new" && mv "$LOG.new" "$LOG"; }
deny() { log "DENIED"; echo "zfs-send-guard: refused" >&2; exit 1; }
case $c in *[!A-Za-z0-9\ _@/:.,=\|\'-]*) deny ;; esac
read -ra w <<< "${c//\'/}"
ds_ok()   { local a; for a in $ALLOWED; do [[ $1 == "$a" ]] && return 0; done; return 1; }
snap_ok() { [[ $1 == *@* ]] && ds_ok "${1%%@*}" && [[ ${1#*@} =~ ^[A-Za-z0-9_:.-]+$ ]]; }
obj_ok()  { ds_ok "$1" || snap_ok "$1"; }
n=${#w[@]}
case "${w[0]:-} ${w[1]:-}" in
  "exit ")
    [ "$n" = 1 ] || deny; log ok; exit 0 ;;
  "echo -n")
    [ "$n" = 2 ] || deny; log ok; exit 0 ;;
  "command -v")
    [ "$n" = 3 ] && [[ ${w[2]} =~ ^(mbuffer|pv|lzop|zstd|gzip|pigz|xz|lz4|socat|busybox)$ ]] || deny
    log ok; command -v "${w[2]}"; exit ;;
  "zpool get")
    [[ $n == 7 && "${w[2]} ${w[3]} ${w[4]}" == "-o value -H" && ${w[5]} =~ ^feature@[a-z_]+$ && ${w[6]} == data ]] || deny
    log ok; exec /usr/sbin/zpool get -o value -H "${w[5]}" data ;;
  "zfs get"|"zfs list")
    [ "$n" -ge 3 ] && obj_ok "${w[n-1]}" || deny
    for a in "${w[@]:2:n-3}"; do [[ $a =~ ^(-[A-Za-z]+|[0-9]+|[a-z][a-z0-9_:,.]*)$ ]] || deny; done
    log ok; exec /usr/sbin/zfs "${w[@]:1}" ;;
  "zfs send")
    mb=0; last=$((n-1))
    if [ "$n" -ge 9 ] && [ "${w[*]:n-7}" = "| mbuffer -q -s 128k -m 16M" ]; then mb=1; last=$((n-8)); fi
    args=(); snaps=0; ds=""
    for ((i=2; i<=last; i++)); do a=${w[i]}
      if [[ $a =~ ^-(n|v|P|nvP|nP|vP|I|i)$ ]]; then args+=("$a")
      elif snap_ok "$a"; then [ -z "$ds" ] && ds=${a%%@*}; [ "${a%%@*}" = "$ds" ] || deny; args+=("$a"); snaps=$((snaps+1))
      else deny; fi
    done
    [ "$snaps" -ge 1 ] && [ "$snaps" -le 2 ] || deny
    log ok
    if [ $mb = 1 ]; then /usr/sbin/zfs send "${args[@]}" | /usr/bin/mbuffer -q -s 128k -m 16M; exit "${PIPESTATUS[0]}"
    else exec /usr/sbin/zfs send "${args[@]}"; fi ;;
  "zfs hold"|"zfs release")
    [ "$n" = 4 ] && [[ ${w[2]} =~ ^syncoid_[A-Za-z0-9_-]+$ ]] && snap_ok "${w[3]}" || deny
    log ok; exec /usr/sbin/zfs "${w[1]}" "${w[2]}" "${w[3]}" ;;
  *) deny ;;
esac
