#!/usr/bin/env python3
"""Synthetic core data for the bench (documents, finance, photos), deterministic.

The pages' core data is a person's documents, finance and photos. On this bench all data is
synthetic (answer Q1). Same shape as rung 0 on laptop: 20 text documents, 2 CSV ledgers,
12 noise JPEG-sized files. Usage: synthetic-core-data.py <outdir>
"""
import os, random, sys
out = sys.argv[1]; rnd = random.Random(20260923)
words = 'invoice lease meeting garden plumber insurance quarterly tax receipt warranty school doctor'.split()
note = 'SYNTHETIC DATA for the seed bench. Not a person\'s data. Generated by tools/synthetic-core-data.py (seed 20260923).\n'
for d in ('documents', 'finance', 'photos'):
    os.makedirs(f'{out}/{d}', exist_ok=True)
    open(f'{out}/{d}/README-SYNTHETIC.txt', 'w').write(note)
for i in range(20):
    body = ' '.join(rnd.choice(words) for _ in range(rnd.randint(80, 400)))
    open(f'{out}/documents/doc-{i:02d}.txt', 'w').write(f'Document {i}\n\n{body}\n')
for name in ('checking', 'savings'):
    with open(f'{out}/finance/{name}-2026.csv', 'w') as f:
        f.write('date,description,amount\n')
        for day in range(1, 250):
            f.write(f'2026-{1 + day // 31:02d}-{1 + day % 28:02d},{rnd.choice(words)},{rnd.uniform(-400, 900):.2f}\n')
for i in range(12):
    open(f'{out}/photos/img-{i:02d}.jpg', 'wb').write(rnd.randbytes(rnd.randint(900_000, 1_800_000)))
